server:
  port: 18080
  servlet:
    context-path: /api
spring:
  # redis
  redis:
    host: 192.168.73.120
    port: 49153
    password: redispw
  # db
  datasource:
    druid:
      url: jdbc:mysql://192.168.73.120:13306/yomi_boot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
      username: root
      password: 123456
      asyncInit: true

# dubbo
dubbo:
  application:
    name: ${spring.application.name}
    qos-port: 22222
    register-mode: instance
    logger: slf4j
  protocol:
    serialization: hessian2
    name: dubbo
    port: -1
  registry:
    address: nacos://192.168.73.120:8848
  provider:
    filter: traceId
  consumer:
    check: false
    listener: invokerListener
    filter: traceId

#es
es:
  open: false
  username: elastic
  password: yDQcXFlNVSm8tm_5lX6u
  uri: 127.0.0.1:9200

# Sa-Token
sa-token:
  # 自定义分组属性
  group: yomi-boot
  # http header 中，从 Authorization 中获取 tokenValue
  token-name: YOMI_TOKEN
  # token 过期时间 30 天
  timeout: 2592000
  # 不过期
  active-timeout: -1
  # token 过期时间自动续期
  auto-renew: true
  # 是否允许同一账号并发登录 （为 true 时允许一起登录，为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # 不打印操作日志
  is-log: false
  # 初始化配置时不打印版本字符画
  isPrint: false
  # 是否从 cookie 中获取 tokenValue
  is-read-cookie: false
  # 是否从 body 中获取 tokenValue
  is-read-body: false

# RocketMQ
rocketmq:
  enable: false
  producer:
    - nameserver: localhost:9876
      group-name: test
    - nameserver: localhost:9876
      group-name: test2
  consumer:
    - nameserver: localhost:9876
      group-name: test
      topic: test
      bean-name: com.yomi.boot.framework.mq.rocketmq.DefaultRocketMqConsumerCallback
    - nameserver: localhost:9876
      group-name: test2
      topic: test2
      bean-name: com.yomi.boot.framework.mq.rocketmq.DefaultRocketMqConsumerCallback

yomi:
  boot:
    logs: crashLog
    rbac-check-auth: rbacCheckDefault