server:
  port: 18080
  servlet:
    context-path: /api/v1
spring:
  # db
  datasource:
    druid:
      url: jdbc:mysql://192.168.2.163:13306/dwei?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
      username: root
      password: 123456
      # db异步初始化
      asyncInit: true
  data:
    # redis
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms

# dubbo
#dubbo:
#  application:
#    name: ${spring.application.name}
#    qos-port: 22222
#    register-mode: instance
#    logger: slf4j
#  protocol:
#    serialization: hessian2
#    name: dubbo
#    port: -1
#  registry:
#    address: nacos://192.168.73.120:8848
#  provider:
#    filter: traceId
#  consumer:
#    check: false
#    listener: invokerListener
#    filter: traceId

#es
#es:
#  open: false
#  username: elastic
#  password: yDQcXFlNVSm8tm_5lX6u
#  uri: 127.0.0.1:9200

# RocketMQ
#rocketmq:
#  enable: false
#  producer:
#    - nameserver: localhost:9876
#      group-name: test
#    - nameserver: localhost:9876
#      group-name: test2
#  consumer:
#    - nameserver: localhost:9876
#      group-name: test
#      topic: test
#      bean-name: com.yomi.boot.framework.mq.rocketmq.DefaultRocketMqConsumerCallback
#    - nameserver: localhost:9876
#      group-name: test2
#      topic: test2
#      bean-name: com.yomi.boot.framework.mq.rocketmq.DefaultRocketMqConsumerCallback

# dwei框架配置
dwei:
  # 日志配置
  logs:
    # 崩溃日志处理器配置
    ex: defaultExLog, crashLog
  api:
    # 忽略权限校验的uri
    ignore: /**/user/login, /**/user/register
