########################################
## 该配置文件为通用配置，一般无需修改
########################################
server:
  # HTTP设置
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  max-http-request-header-size: 8192
  # 压缩配置
  compression:
    enabled: true
    mime-types: application/json,text/javascript,application/javascript,application/x-javascript,application/xml,text/html,text/xml,text/plain,image/jpeg,image/gif,image/x-icon
    min-response-size: 2048
  # tomcat配置
  tomcat:
    #当所有可能的请求处理线程都在使用时，传入连接请求的最大队列长度
    acceptCount: 200
    # tomcat线程池配置
    threads:
      max: 50
      min-spare: 20
    remoteip:
      remote-ip-header: X-FORWARDED-FOR
    uriEncoding: UTF-8
    # 自定义临时文件存放目录
    basedir: ./tmp/${spring.application.name}/tomcat_tmp
    accesslog:
      enabled: false
      directory: logs
      prefix: server
      buffered: true
      requestAttributesEnabled: false
      fileDateFormat: -yyyyMMdd

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
  session:
    timeout: 1200S
    store-type: redis
  main:
    banner-mode: log
  output:
    ansi:
      enabled: DETECT
  # db
  datasource:
    druid:
      name: masterDs
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 连接池配置
      # 连接池初始化连接数
      initialSize: 15
      # 连接池最小连接数
      minIdle: 15
      # 连接池最大连接数
      maxActive: 30
      # 获取连接时最大等待时间，单位毫秒
      maxWait: 6000
      # 判断空闲连接间隔时间，单位毫秒
      timeBetweenEvictionRunsMillis: 6000
      # 连接在连接池中的最小生命周期，单位毫秒
      minEvictableIdleTimeMillis: 300000
      # 用来检测连接是否有效的sql语句，必须是select
      validationQuery: SELECT 'x'
      # 检测连接是否有效的超时时间，单位秒
      validationQueryTimeout: 10
      # 是否进行如果空闲时间大于timeBetweenEvictionRunsMillis检测连接是否有效
      testWhileIdle: true
      # 是否进行申请连接的时候检测连接是否有效
      testOnBorrow: false
      # 是否进行归还连接的时候检测连接是否有效
      testOnReturn: false
      # 是否缓存preparedStatement，MYSQL下建议关闭，ORACLE建议开启
      poolPreparedStatements: false
      # PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: -1
      # 是否强制性回收超时的连接
      # 设置这个值的时候需要注意 如果你的连接操作需要很长时间，那么需要关闭这个设置或增加连接强制回收时间
      removeAbandoned: true
      # 连接强制回收时间，单位秒
      removeAbandonedTimeout: 1800
      # Filter配置
      filters: stat,wall,slf4j
      filter:
        stat:
          # 开启SQL合并和慢查询统计功能
          merge-sql: true
          slow-sql-millis: 2000
      # 配置StatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/${spring.datasource.druid.name}/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
        profile-enable: true
      # StatViewServlet
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/${spring.datasource.druid.name}/*
        reset-enable: false
        login-username: admin
        login-password: 123456
        # IP白名单，这里默认只允许当前PC查看
        allow: 127.0.0.1
  data:
    # redis
    redis:
      database: 0
      timeout: 3s

# 日志设置
logging:
  config: classpath:config/log/log4j2-dev.xml
  register-shutdown-hook: true
  level:
    root: info
    org: info
    com: info
    org.apache.dubbo: info
    com.dwei: debug

# 加密设置
jasypt:
  encryptor:
    bean: standardConfigEncryptor

# spring-boot-actuator 监控组件管理配置
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.dwei.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:config/mybatis/mybatis-config.xml

# MyBatis plus配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.dwei.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Sa-Token
sa-token:
  # 自定义分组属性
  group: ${spring.application.name}
  # http header 中，从 Authorization 中获取 tokenValue
  token-name: auth_token
  # token 过期时间 30 天
  timeout: 2592000
  # 不过期
  active-timeout: -1
  # token风格 使用uuid风格, 只不过去掉了中划线
  token-style: simple-uuid
  # token 过期时间自动续期
  auto-renew: true
  # 是否允许同一账号并发登录 （为 true 时允许一起登录，为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # 不打印操作日志
  is-log: false
  # 初始化配置时不打印版本字符画
  isPrint: false
  # 是否从 cookie 中获取 tokenValue
  is-read-cookie: false
  # 是否从 body 中获取 tokenValue
  is-read-body: false